---
# tasks file for postgres_test
- name: Create test user
  become: yes
  become_user: postgres
  no_log: true
  postgresql_user:
    name: test
    role_attr_flags: LOGIN
    password: "{{ TEST_PWD }}"
  when: inventory_hostname == 'master'

- name: Create test database for test user
  become: yes
  become_user: postgres
  postgresql_db:
    name: testdb
    owner: test
  when: inventory_hostname == 'master'

- name: Create test table for test user
  postgresql_table:
    login_host: "{{ master_ip }}"
    login_user: test
    login_password: "{{ TEST_PWD }}"
    db: testdb
    name: test_table
    columns:
    - id serial primary key
    - dt timestamp default now()
    - value text
  when: inventory_hostname == 'master'

- name: Insert row in test table on master
  postgresql_query:
    login_host: "{{ master_ip }}"
    login_user: test
    login_password: "{{ TEST_PWD }}"
    db: testdb
    query: "insert into test_table (value) values ('hello from master! you can''t insert')"
  when: inventory_hostname == 'master'
   
- name: Read row in test table on replica
  postgresql_query:
    login_host: "{{ replica_ip }}"
    login_user: test
    login_password: "{{ TEST_PWD }}"
    db: testdb
    query: "select * from test_table order by id desc limit 1"
  register: read_data_from_replica
  when: inventory_hostname == 'replica'

- name: Print last test row from replica
  debug: var=read_data_from_replica.query_result
  when: inventory_hostname == 'replica'

